const events=[
{id:'01',title:'“蓝桥杯”程序设计校内训练营',source:'school',sourceName:'学校通知',type:'工作坊',date:'9月20日',time:'每周六 19:00',location:'实验楼 A402',deadline:'9月24日 22:00',limit:'面向全校学生',desc:'面向全校学生，夯实基础，循序渐进提升程序设计能力。',newbie:true,free:true},
{id:'02',title:'AI应用入门公开课',source:'college',sourceName:'计算机学院',type:'讲座',date:'9月19日',time:'19:00',location:'计算机学院教学楼',deadline:'无需报名',limit:'全校学生',desc:'从认识 AI 到动手使用，90 分钟带你打开 AI 应用新世界。',newbie:true,free:true},
{id:'03',title:'大学生创新创业项目团队招募',source:'school',sourceName:'学校通知',type:'招募',date:'长期招募',time:'每周投入4小时以上',location:'线上沟通',deadline:'9月22日 18:00',limit:'需提交自我介绍',desc:'招募开发、设计、材料成员，寻找志同道合的项目伙伴。',newbie:false,free:true},
{id:'04',title:'数学建模竞赛经验分享会',source:'school',sourceName:'学校通知',type:'讲座',date:'9月18日',time:'19:30',location:'线上直播',deadline:'活动已结束',limit:'不限专业',desc:'往届参赛同学经验分享，直播已结束，活动方预计9月20日上传回放。',newbie:true,free:true},
{id:'05',title:'校园公益志愿服务活动',source:'school',sourceName:'学校通知',type:'活动',date:'9月27日',time:'08:30—17:00',location:'校门集合',deadline:'9月20日 12:00',limit:'预计服务8小时',desc:'参与公益服务，记得提前到场签到，收获一次真实的实践体验。',newbie:true,free:true},
{id:'06',title:'Web开发零基础学习小组',source:'student',sourceName:'学生自主发布',type:'招募',date:'9月23日',time:'每周二 19:30',location:'线上会议',deadline:'满员即止',limit:'限30人',desc:'从 HTML、CSS 开始，共 6 周学习，适合完全没有基础的同学。',newbie:true,free:true},
{id:'07',title:'AI创新应用挑战赛',source:'school',sourceName:'学校通知',type:'竞赛',date:'9月21日',time:'组队报名',location:'线上提交',deadline:'9月21日 18:00',limit:'2—4人组队',desc:'提交 AI 意向登记，10月20日前提交作品，优秀作品有展示机会。',newbie:true,free:true},
{id:'08',title:'校园软件项目组招募',source:'student',sourceName:'学生自主发布',type:'招募',date:'长期招募',time:'每周投入5小时',location:'线上沟通',deadline:'满员即止',limit:'大一、大二优先',desc:'开发校园实用工具，欢迎想了解 Git 基本操作的同学加入。',newbie:true,free:true},
{id:'09',title:'程序设计训练营补充通知',source:'school',sourceName:'学校通知',type:'活动',date:'9月21日',time:'19:30',location:'实验楼 A402',deadline:'报名截止',limit:'已报名同学',desc:'因场地调整，首次训练改为9月21日，地点改至实验楼 A402。',newbie:false,free:true},
{id:'10',title:'前端开发经验交流会',source:'college',sourceName:'计算机学院',type:'讲座',date:'9月19日',time:'15:00—16:30',location:'线下 TA201 / 线上直播',deadline:'无需报名',limit:'全校学生',desc:'和学长学姐聊聊前端学习路径、作品集与实习准备。',newbie:true,free:true},
{id:'11',title:'大学生科研入门分享会',source:'school',sourceName:'学校通知',type:'讲座',date:'9月21日',time:'19:00—20:30',location:'线上',deadline:'无需报名',limit:'全校学生',desc:'介绍文献检索、学生科研项目和导师联系方法。',newbie:true,free:true},
{id:'12',title:'全国高校计算机能力挑战赛',source:'school',sourceName:'学校通知',type:'竞赛',date:'10月5日',time:'个人参赛',location:'线上',deadline:'10月5日 23:59',limit:'面向本科生',desc:'全国性计算机能力挑战赛，个人参赛，具体费用信息待官方提供。',newbie:false,free:false},
{id:'13',title:'科研助理招募',source:'college',sourceName:'计算机学院',type:'招募',date:'长期招募',time:'每周投入6小时',location:'实验室',deadline:'9月21日',limit:'大二及以上',desc:'协助数据整理和实验工作，适合希望了解科研工作的同学。',newbie:false,free:true},
{id:'14',title:'Git与GitHub零基础工作坊',source:'school',sourceName:'学校通知',type:'工作坊',date:'9月21日',time:'19:00—20:30',location:'线下教室',deadline:'需提前预约',limit:'限40人',desc:'主要面向大一新生，学习版本控制和团队协作的第一步。',newbie:true,free:true},
{id:'15',title:'AI应用创意挑战',source:'school',sourceName:'学校通知',type:'竞赛',date:'9月23日',time:'提交创意方案',location:'线上提交',deadline:'9月23日 23:59',limit:'个人或团队',desc:'先提交创意方案，9月30日前提交最终作品，进入展示环节后再组队。',newbie:true,free:true},
{id:'16',title:'校园摄影志愿者招募',source:'student',sourceName:'学生自主发布',type:'招募',date:'长期招募',time:'灵活安排',location:'校内大型活动',deadline:'报名时间未注明',limit:'需作品或设备',desc:'参与校内大型活动摄影，适合喜欢记录校园生活的同学。',newbie:false,free:true},
{id:'17',title:'Python程序设计学习资料合集',source:'student',sourceName:'学生自主发布',type:'资源',date:'长期开放',time:'随时学习',location:'在线网盘',deadline:'9月22日前更新',limit:'公开资源',desc:'包含课程、练习和项目案例，资料长期开放，后续持续更新。',newbie:true,free:true},
{id:'18',title:'网络安全兴趣交流小组',source:'student',sourceName:'学生自主发布',type:'招募',date:'9月19日',time:'19:30',location:'线上交流',deadline:'持续招募',limit:'不限基础',desc:'首次交流后每两周开展一次，面向 CTF、Web 安全等方向感兴趣的学生。',newbie:true,free:true},
{id:'19',title:'学生创新项目路演观摩',source:'school',sourceName:'学校通知',type:'活动',date:'9月20日',time:'14:30',location:'路演现场',deadline:'现场仍有余位',limit:'可接受候补',desc:'原报名截止时间已过，现场仍有余位，可接受候补入场。',newbie:true,free:true},
{id:'20',title:'创新创业项目团队补充说明',source:'school',sourceName:'学校通知',type:'招募',date:'9月22日',time:'18:00截止',location:'线上提交',deadline:'9月22日 18:00',limit:'设计与材料成员',desc:'开发方向名额已满，现主要补充设计与材料成员，已投递者无需重复提交。',newbie:false,free:true},
{id:'21',title:'计算机学院AI产品设计分享会',source:'college',sourceName:'计算机学院',type:'讲座',date:'9月20日',time:'19:00',location:'明德楼 B203',deadline:'无需报名',limit:'座位有限',desc:'计算机学院发布，分享 AI 产品从想法到落地的设计实践。',newbie:true,free:true},
{id:'22',title:'学生发起｜周末羽毛球约球',source:'student',sourceName:'学生自主发布',type:'活动',date:'9月20日',time:'16:00',location:'校体育馆',deadline:'人数满即止',limit:'6—8人，费用 AA',desc:'学生个人发布，欢迎新同学一起运动，场地待最终确认。',newbie:true,free:false}
];
const state={saved:JSON.parse(localStorage.getItem('saved')||'[]'),joined:JSON.parse(localStorage.getItem('joined')||'[]'),published:JSON.parse(localStorage.getItem('published')||'[]')};let activePreset='all';
const $=s=>document.querySelector(s);const allEvents=()=>[...events,...state.published];
function save(){localStorage.setItem('saved',JSON.stringify(state.saved));localStorage.setItem('joined',JSON.stringify(state.joined));localStorage.setItem('published',JSON.stringify(state.published))}
function card(e){return `<article class="event-card" data-id="${e.id}"><div class="card-top"><span class="tag ${e.deadline.includes('9月')?'coral':''}">${e.type}</span><button class="bookmark ${state.saved.includes(e.id)?'saved':''}" data-save="${e.id}" aria-label="收藏">${state.saved.includes(e.id)?'♥':'♡'}</button></div><h3>${e.title}</h3><p class="desc">${e.desc}</p><div class="meta"><span>◷ ${e.date} · ${e.time}</span><strong>${e.sourceName}</strong></div></article>`}
function render(){const q=$('#searchInput').value.trim().toLowerCase(),source=$('#sourceFilter').value,type=$('#typeFilter').value;let list=allEvents().filter(e=>(!q||(e.title+e.desc+e.type+e.sourceName).toLowerCase().includes(q))&&(source==='all'||e.source===source)&&(type==='all'||e.type===type));if(activePreset==='new')list=list.filter(e=>e.newbie);if(activePreset==='soon')list=list.filter(e=>e.deadline.includes('9月2')||e.deadline.includes('9月21')||e.deadline.includes('9月22')||e.deadline.includes('9月23')||e.deadline.includes('9月24'));if(activePreset==='free')list=list.filter(e=>e.free);$('#eventGrid').innerHTML=list.map(card).join('');$('#emptyState').hidden=list.length>0;updateMine();renderCalendar(list)}
function updateMine(){const items=allEvents().filter(e=>state.saved.includes(e.id)||state.joined.includes(e.id));$('#savedCount').textContent=state.saved.length;$('#joinedCount').textContent=state.joined.length;$('#mineList').innerHTML=items.map(e=>`<div class="mine-item"><b>${state.joined.includes(e.id)?'✓ ':''}${e.title}</b><small>${e.date} · ${e.location} · ${state.saved.includes(e.id)?'已收藏':''}</small></div>`).join('')}
function renderCalendar(list=allEvents()){const days=[['周五','19'],['周六','20'],['周日','21'],['周一','22'],['周二','23'],['周三','24'],['周四','25']];$('#weekStrip').innerHTML=days.map((d,i)=>`<button class="day ${i===1?'selected':''}">${d[0]}<b>${d[1]}</b></button>`).join('');$('#calendarList').innerHTML=list.slice(0,3).map(e=>`<div class="calendar-item"><span class="calendar-time">${e.time.split('—')[0]}</span><div><b>${e.title}</b><small>${e.location} · ${e.sourceName}</small></div></div>`).join('')}
function openDetail(id){const e=allEvents().find(x=>x.id===id);if(!e)return;$('#detailContent').innerHTML=`<button class="close" data-close>×</button><div class="detail-header"><span class="tag">${e.type} · ${e.sourceName}</span><button class="bookmark ${state.saved.includes(e.id)?'saved':''}" data-save="${e.id}">${state.saved.includes(e.id)?'♥':'♡'}</button></div><h2 class="detail-title">${e.title}</h2><p class="detail-desc">${e.desc}</p><div class="detail-info"><div><small>时间</small><b>${e.date} · ${e.time}</b></div><div><small>地点</small><b>${e.location}</b></div><div><small>报名截止</small><b>${e.deadline}</b></div><div><small>参与要求</small><b>${e.limit}</b></div></div><button class="button primary full" id="joinBtn">${state.joined.includes(e.id)?'取消报名':'报名参加'} <span>→</span></button>`;$('#detailModal').hidden=false;$('#joinBtn').onclick=()=>{if(state.joined.includes(e.id))state.joined=state.joined.filter(x=>x!==e.id);else state.joined.push(e.id);save();openDetail(id);render();toast(state.joined.includes(e.id)?'报名成功，已加入我的日程':'已取消报名')};}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
document.addEventListener('click',e=>{const saveId=e.target.dataset.save;if(saveId){e.stopPropagation();state.saved.includes(saveId)?state.saved=state.saved.filter(x=>x!==saveId):state.saved.push(saveId);save();render();toast(state.saved.includes(saveId)?'已收藏到我的机会库':'已取消收藏');return}const cardEl=e.target.closest('.event-card');if(cardEl)openDetail(cardEl.dataset.id);if(e.target.matches('[data-close]')||e.target=== $('#detailModal')||e.target===$('#publishModal')){e.target.closest('.modal-backdrop').hidden=true}if(e.target.id==='openPublish'||e.target.id==='quickPublish')$('#publishModal').hidden=false;if(e.target.matches('.chip')){document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');activePreset=e.target.dataset.preset;render()}});
['searchInput','sourceFilter','typeFilter'].forEach(id=>$( '#'+id).addEventListener('input',render));$('#publishForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.published.unshift({id:'p'+Date.now(),title:f.get('title'),source:'student',sourceName:'学生自主发布',type:f.get('type'),date:f.get('date'),time:'待确认',location:f.get('location'),deadline:'报名信息请关注发布者',limit:f.get('limit')||'不限',desc:f.get('description'),newbie:true,free:true});save();e.target.reset();$('#publishModal').hidden=true;render();location.hash='#events';toast('发布成功，已展示在机会列表中')});
render();
